services:
  - type: web
    name: unizoom-server
    runtime: node
    region: ohio
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
